//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace ftpUpLoader.ArmServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="url:armservice")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback MywmOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKKmHostNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendNotificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendKKmZInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendKKmZInfoZOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmZreportSendedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ftpUpLoader.Properties.Settings.Default.ftpUpLoader_ArmServices_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event MywmCompletedEventHandler MywmCompleted;
        
        /// <remarks/>
        public event UpdateKKmHostNameCompletedEventHandler UpdateKKmHostNameCompleted;
        
        /// <remarks/>
        public event SendNotificationCompletedEventHandler SendNotificationCompleted;
        
        /// <remarks/>
        public event SendKKmZInfoCompletedEventHandler SendKKmZInfoCompleted;
        
        /// <remarks/>
        public event SendKKmZInfoZCompletedEventHandler SendKKmZInfoZCompleted;
        
        /// <remarks/>
        public event ConfirmZreportSendedCompletedEventHandler ConfirmZreportSendedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/HelloWorld", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/Mywm", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Mywm(string fn, string ln) {
            object[] results = this.Invoke("Mywm", new object[] {
                        fn,
                        ln});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MywmAsync(string fn, string ln) {
            this.MywmAsync(fn, ln, null);
        }
        
        /// <remarks/>
        public void MywmAsync(string fn, string ln, object userState) {
            if ((this.MywmOperationCompleted == null)) {
                this.MywmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMywmOperationCompleted);
            }
            this.InvokeAsync("Mywm", new object[] {
                        fn,
                        ln}, this.MywmOperationCompleted, userState);
        }
        
        private void OnMywmOperationCompleted(object arg) {
            if ((this.MywmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MywmCompleted(this, new MywmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/UpdateKKmHostName", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateKKmHostName(int kkm_num, string kkm_hostname, string kkm_suffix) {
            object[] results = this.Invoke("UpdateKKmHostName", new object[] {
                        kkm_num,
                        kkm_hostname,
                        kkm_suffix});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateKKmHostNameAsync(int kkm_num, string kkm_hostname, string kkm_suffix) {
            this.UpdateKKmHostNameAsync(kkm_num, kkm_hostname, kkm_suffix, null);
        }
        
        /// <remarks/>
        public void UpdateKKmHostNameAsync(int kkm_num, string kkm_hostname, string kkm_suffix, object userState) {
            if ((this.UpdateKKmHostNameOperationCompleted == null)) {
                this.UpdateKKmHostNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKKmHostNameOperationCompleted);
            }
            this.InvokeAsync("UpdateKKmHostName", new object[] {
                        kkm_num,
                        kkm_hostname,
                        kkm_suffix}, this.UpdateKKmHostNameOperationCompleted, userState);
        }
        
        private void OnUpdateKKmHostNameOperationCompleted(object arg) {
            if ((this.UpdateKKmHostNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKKmHostNameCompleted(this, new UpdateKKmHostNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/SendNotification", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendNotification(string _header, string _message, int _type) {
            object[] results = this.Invoke("SendNotification", new object[] {
                        _header,
                        _message,
                        _type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendNotificationAsync(string _header, string _message, int _type) {
            this.SendNotificationAsync(_header, _message, _type, null);
        }
        
        /// <remarks/>
        public void SendNotificationAsync(string _header, string _message, int _type, object userState) {
            if ((this.SendNotificationOperationCompleted == null)) {
                this.SendNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendNotificationOperationCompleted);
            }
            this.InvokeAsync("SendNotification", new object[] {
                        _header,
                        _message,
                        _type}, this.SendNotificationOperationCompleted, userState);
        }
        
        private void OnSendNotificationOperationCompleted(object arg) {
            if ((this.SendNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendNotificationCompleted(this, new SendNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/SendKKmZInfo", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendKKmZInfo(string terem_1c, string kkm_name, System.DateTime date, bool worked, System.DateTime lasttime_online) {
            object[] results = this.Invoke("SendKKmZInfo", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        worked,
                        lasttime_online});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendKKmZInfoAsync(string terem_1c, string kkm_name, System.DateTime date, bool worked, System.DateTime lasttime_online) {
            this.SendKKmZInfoAsync(terem_1c, kkm_name, date, worked, lasttime_online, null);
        }
        
        /// <remarks/>
        public void SendKKmZInfoAsync(string terem_1c, string kkm_name, System.DateTime date, bool worked, System.DateTime lasttime_online, object userState) {
            if ((this.SendKKmZInfoOperationCompleted == null)) {
                this.SendKKmZInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendKKmZInfoOperationCompleted);
            }
            this.InvokeAsync("SendKKmZInfo", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        worked,
                        lasttime_online}, this.SendKKmZInfoOperationCompleted, userState);
        }
        
        private void OnSendKKmZInfoOperationCompleted(object arg) {
            if ((this.SendKKmZInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendKKmZInfoCompleted(this, new SendKKmZInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/SendKKmZInfoZ", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendKKmZInfoZ(string terem_1c, string kkm_name, System.DateTime date, string zfile, System.DateTime zdate) {
            object[] results = this.Invoke("SendKKmZInfoZ", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        zfile,
                        zdate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendKKmZInfoZAsync(string terem_1c, string kkm_name, System.DateTime date, string zfile, System.DateTime zdate) {
            this.SendKKmZInfoZAsync(terem_1c, kkm_name, date, zfile, zdate, null);
        }
        
        /// <remarks/>
        public void SendKKmZInfoZAsync(string terem_1c, string kkm_name, System.DateTime date, string zfile, System.DateTime zdate, object userState) {
            if ((this.SendKKmZInfoZOperationCompleted == null)) {
                this.SendKKmZInfoZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendKKmZInfoZOperationCompleted);
            }
            this.InvokeAsync("SendKKmZInfoZ", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        zfile,
                        zdate}, this.SendKKmZInfoZOperationCompleted, userState);
        }
        
        private void OnSendKKmZInfoZOperationCompleted(object arg) {
            if ((this.SendKKmZInfoZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendKKmZInfoZCompleted(this, new SendKKmZInfoZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("url:armservice/ConfirmZreportSended", RequestNamespace="url:armservice", ResponseNamespace="url:armservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmZreportSended(string terem_1c, string kkm_name, System.DateTime date, string zfile, bool sended) {
            object[] results = this.Invoke("ConfirmZreportSended", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        zfile,
                        sended});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmZreportSendedAsync(string terem_1c, string kkm_name, System.DateTime date, string zfile, bool sended) {
            this.ConfirmZreportSendedAsync(terem_1c, kkm_name, date, zfile, sended, null);
        }
        
        /// <remarks/>
        public void ConfirmZreportSendedAsync(string terem_1c, string kkm_name, System.DateTime date, string zfile, bool sended, object userState) {
            if ((this.ConfirmZreportSendedOperationCompleted == null)) {
                this.ConfirmZreportSendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmZreportSendedOperationCompleted);
            }
            this.InvokeAsync("ConfirmZreportSended", new object[] {
                        terem_1c,
                        kkm_name,
                        date,
                        zfile,
                        sended}, this.ConfirmZreportSendedOperationCompleted, userState);
        }
        
        private void OnConfirmZreportSendedOperationCompleted(object arg) {
            if ((this.ConfirmZreportSendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmZreportSendedCompleted(this, new ConfirmZreportSendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MywmCompletedEventHandler(object sender, MywmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MywmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MywmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateKKmHostNameCompletedEventHandler(object sender, UpdateKKmHostNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateKKmHostNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateKKmHostNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendNotificationCompletedEventHandler(object sender, SendNotificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendKKmZInfoCompletedEventHandler(object sender, SendKKmZInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendKKmZInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendKKmZInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendKKmZInfoZCompletedEventHandler(object sender, SendKKmZInfoZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendKKmZInfoZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendKKmZInfoZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ConfirmZreportSendedCompletedEventHandler(object sender, ConfirmZreportSendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmZreportSendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmZreportSendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591