//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Исходное имя файла:
// Дата создания: 16.12.2014 10:50:42
namespace RBClientUpdateApplication
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для RBMEntities.
    /// </summary>
    public partial class RBMEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Инициализирует новый объект RBMEntities, используя строку соединения из раздела "RBMEntities" файла конфигурации приложения.
        /// </summary>
        public RBMEntities() : 
                base("name=RBMEntities", "RBMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Инициализируйте новый объект RBMEntities.
        /// </summary>
        public RBMEntities(string connectionString) : 
                base(connectionString, "RBMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Инициализируйте новый объект RBMEntities.
        /// </summary>
        public RBMEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "RBMEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// В схеме отсутствуют комментарии для t_Teremok.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<t_Teremok> t_Teremok
        {
            get
            {
                if ((this._t_Teremok == null))
                {
                    this._t_Teremok = base.CreateQuery<t_Teremok>("[t_Teremok]");
                }
                return this._t_Teremok;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<t_Teremok> _t_Teremok;
        /// <summary>
        /// В схеме отсутствуют комментарии для t_Teremok.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTot_Teremok(t_Teremok t_Teremok)
        {
            base.AddObject("t_Teremok", t_Teremok);
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для RBMModel.t_Teremok.
    /// </summary>
    /// <KeyProperties>
    /// teremok_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RBMModel", Name="t_Teremok")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class t_Teremok : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Создайте новый объект t_Teremok.
        /// </summary>
        /// <param name="teremok_id">Начальное значение teremok_id.</param>
        /// <param name="teremok_name">Начальное значение teremok_name.</param>
        /// <param name="teremok_state">Начальное значение teremok_state.</param>
        /// <param name="teremok_need_update">Начальное значение teremok_need_update.</param>
        /// <param name="teremok_use_ARM">Начальное значение teremok_use_ARM.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static t_Teremok Createt_Teremok(int teremok_id, string teremok_name, int teremok_state, bool teremok_need_update, bool teremok_use_ARM)
        {
            t_Teremok t_Teremok = new t_Teremok();
            t_Teremok.teremok_id = teremok_id;
            t_Teremok.teremok_name = teremok_name;
            t_Teremok.teremok_state = teremok_state;
            t_Teremok.teremok_need_update = teremok_need_update;
            t_Teremok.teremok_use_ARM = teremok_use_ARM;
            return t_Teremok;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_id.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int teremok_id
        {
            get
            {
                return this._teremok_id;
            }
            set
            {
                this.Onteremok_idChanging(value);
                this.ReportPropertyChanging("teremok_id");
                this._teremok_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_id");
                this.Onteremok_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _teremok_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_idChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_name.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_name
        {
            get
            {
                return this._teremok_name;
            }
            set
            {
                this.Onteremok_nameChanging(value);
                this.ReportPropertyChanging("teremok_name");
                this._teremok_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teremok_name");
                this.Onteremok_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_nameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_nameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_address.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_address
        {
            get
            {
                return this._teremok_address;
            }
            set
            {
                this.Onteremok_addressChanging(value);
                this.ReportPropertyChanging("teremok_address");
                this._teremok_address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_address");
                this.Onteremok_addressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_address;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_addressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_addressChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_state.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int teremok_state
        {
            get
            {
                return this._teremok_state;
            }
            set
            {
                this.Onteremok_stateChanging(value);
                this.ReportPropertyChanging("teremok_state");
                this._teremok_state = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_state");
                this.Onteremok_stateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _teremok_state;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_stateChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_stateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1C.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_1C
        {
            get
            {
                return this._teremok_1C;
            }
            set
            {
                this.Onteremok_1CChanging(value);
                this.ReportPropertyChanging("teremok_1C");
                this._teremok_1C = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_1C");
                this.Onteremok_1CChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_1C;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1CChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1CChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_need_update.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool teremok_need_update
        {
            get
            {
                return this._teremok_need_update;
            }
            set
            {
                this.Onteremok_need_updateChanging(value);
                this.ReportPropertyChanging("teremok_need_update");
                this._teremok_need_update = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_need_update");
                this.Onteremok_need_updateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _teremok_need_update;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_need_updateChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_need_updateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_pass.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_pass
        {
            get
            {
                return this._teremok_pass;
            }
            set
            {
                this.Onteremok_passChanging(value);
                this.ReportPropertyChanging("teremok_pass");
                this._teremok_pass = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_pass");
                this.Onteremok_passChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_pass;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_passChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_passChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_use_ARM.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool teremok_use_ARM
        {
            get
            {
                return this._teremok_use_ARM;
            }
            set
            {
                this.Onteremok_use_ARMChanging(value);
                this.ReportPropertyChanging("teremok_use_ARM");
                this._teremok_use_ARM = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_use_ARM");
                this.Onteremok_use_ARMChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _teremok_use_ARM;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_use_ARMChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_use_ARMChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_prov.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_prov
        {
            get
            {
                return this._teremok_prov;
            }
            set
            {
                this.Onteremok_provChanging(value);
                this.ReportPropertyChanging("teremok_prov");
                this._teremok_prov = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_prov");
                this.Onteremok_provChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_prov;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_provChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_provChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_prov_rezerv.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_prov_rezerv
        {
            get
            {
                return this._teremok_prov_rezerv;
            }
            set
            {
                this.Onteremok_prov_rezervChanging(value);
                this.ReportPropertyChanging("teremok_prov_rezerv");
                this._teremok_prov_rezerv = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_prov_rezerv");
                this.Onteremok_prov_rezervChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_prov_rezerv;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_prov_rezervChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_prov_rezervChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa1.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_kassa1
        {
            get
            {
                return this._teremok_kassa1;
            }
            set
            {
                this.Onteremok_kassa1Changing(value);
                this.ReportPropertyChanging("teremok_kassa1");
                this._teremok_kassa1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_kassa1");
                this.Onteremok_kassa1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_kassa1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa1Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa1Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa2.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_kassa2
        {
            get
            {
                return this._teremok_kassa2;
            }
            set
            {
                this.Onteremok_kassa2Changing(value);
                this.ReportPropertyChanging("teremok_kassa2");
                this._teremok_kassa2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_kassa2");
                this.Onteremok_kassa2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_kassa2;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa2Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa2Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa3.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_kassa3
        {
            get
            {
                return this._teremok_kassa3;
            }
            set
            {
                this.Onteremok_kassa3Changing(value);
                this.ReportPropertyChanging("teremok_kassa3");
                this._teremok_kassa3 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_kassa3");
                this.Onteremok_kassa3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_kassa3;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa3Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa3Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa4.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_kassa4
        {
            get
            {
                return this._teremok_kassa4;
            }
            set
            {
                this.Onteremok_kassa4Changing(value);
                this.ReportPropertyChanging("teremok_kassa4");
                this._teremok_kassa4 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_kassa4");
                this.Onteremok_kassa4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_kassa4;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa4Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_kassa4Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm1.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> teremok_numberkkm1
        {
            get
            {
                return this._teremok_numberkkm1;
            }
            set
            {
                this.Onteremok_numberkkm1Changing(value);
                this.ReportPropertyChanging("teremok_numberkkm1");
                this._teremok_numberkkm1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_numberkkm1");
                this.Onteremok_numberkkm1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm1Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm1Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm2.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> teremok_numberkkm2
        {
            get
            {
                return this._teremok_numberkkm2;
            }
            set
            {
                this.Onteremok_numberkkm2Changing(value);
                this.ReportPropertyChanging("teremok_numberkkm2");
                this._teremok_numberkkm2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_numberkkm2");
                this.Onteremok_numberkkm2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm2;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm2Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm2Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm3.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> teremok_numberkkm3
        {
            get
            {
                return this._teremok_numberkkm3;
            }
            set
            {
                this.Onteremok_numberkkm3Changing(value);
                this.ReportPropertyChanging("teremok_numberkkm3");
                this._teremok_numberkkm3 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_numberkkm3");
                this.Onteremok_numberkkm3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm3;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm3Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm3Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm4.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> teremok_numberkkm4
        {
            get
            {
                return this._teremok_numberkkm4;
            }
            set
            {
                this.Onteremok_numberkkm4Changing(value);
                this.ReportPropertyChanging("teremok_numberkkm4");
                this._teremok_numberkkm4 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_numberkkm4");
                this.Onteremok_numberkkm4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm4;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm4Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_numberkkm4Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_parent.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_parent
        {
            get
            {
                return this._teremok_parent;
            }
            set
            {
                this.Onteremok_parentChanging(value);
                this.ReportPropertyChanging("teremok_parent");
                this._teremok_parent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_parent");
                this.Onteremok_parentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_parent;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_parentChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_parentChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1c82.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> teremok_1c82
        {
            get
            {
                return this._teremok_1c82;
            }
            set
            {
                this.Onteremok_1c82Changing(value);
                this.ReportPropertyChanging("teremok_1c82");
                this._teremok_1c82 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_1c82");
                this.Onteremok_1c82Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _teremok_1c82;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1c82Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1c82Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1c82_date.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> teremok_1c82_date
        {
            get
            {
                return this._teremok_1c82_date;
            }
            set
            {
                this.Onteremok_1c82_dateChanging(value);
                this.ReportPropertyChanging("teremok_1c82_date");
                this._teremok_1c82_date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teremok_1c82_date");
                this.Onteremok_1c82_dateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _teremok_1c82_date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1c82_dateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_1c82_dateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства deleted.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this.OndeletedChanging(value);
                this.ReportPropertyChanging("deleted");
                this._deleted = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("deleted");
                this.OndeletedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _deleted;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndeletedChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndeletedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ip.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ip
        {
            get
            {
                return this._ip;
            }
            set
            {
                this.OnipChanging(value);
                this.ReportPropertyChanging("ip");
                this._ip = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ip");
                this.OnipChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ip;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnipChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnipChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_city.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string teremok_city
        {
            get
            {
                return this._teremok_city;
            }
            set
            {
                this.Onteremok_cityChanging(value);
                this.ReportPropertyChanging("teremok_city");
                this._teremok_city = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("teremok_city");
                this.Onteremok_cityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _teremok_city;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_cityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onteremok_cityChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства original_id.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> original_id
        {
            get
            {
                return this._original_id;
            }
            set
            {
                this.Onoriginal_idChanging(value);
                this.ReportPropertyChanging("original_id");
                this._original_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("original_id");
                this.Onoriginal_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _original_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onoriginal_idChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onoriginal_idChanged();
    }
}
