//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Исходное имя файла:
// Дата создания: 21.05.2015 13:33:58
namespace ADOProxy.Service1
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для RBMEntities2.
    /// </summary>
    public partial class RBMEntities2 : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Инициализируйте новый объект RBMEntities2.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RBMEntities2(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Models", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ADOProxy.Service1", typeName.Substring(6)), false);
            }
            return null;
        }
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ADOProxy.Service1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для t_Teremok.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<t_Teremok> t_Teremok
        {
            get
            {
                if ((this._t_Teremok == null))
                {
                    this._t_Teremok = base.CreateQuery<t_Teremok>("t_Teremok");
                }
                return this._t_Teremok;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<t_Teremok> _t_Teremok;
        /// <summary>
        /// В схеме отсутствуют комментарии для t_Teremok.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTot_Teremok(t_Teremok t_Teremok)
        {
            base.AddObject("t_Teremok", t_Teremok);
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для Models.t_Teremok.
    /// </summary>
    /// <KeyProperties>
    /// teremok_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("t_Teremok")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("teremok_id")]
    public partial class t_Teremok : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект t_Teremok.
        /// </summary>
        /// <param name="teremok_id">Начальное значение teremok_id.</param>
        /// <param name="teremok_name">Начальное значение teremok_name.</param>
        /// <param name="teremok_state">Начальное значение teremok_state.</param>
        /// <param name="teremok_need_update">Начальное значение teremok_need_update.</param>
        /// <param name="teremok_use_ARM">Начальное значение teremok_use_ARM.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static t_Teremok Createt_Teremok(int teremok_id, string teremok_name, int teremok_state, bool teremok_need_update, bool teremok_use_ARM)
        {
            t_Teremok t_Teremok = new t_Teremok();
            t_Teremok.teremok_id = teremok_id;
            t_Teremok.teremok_name = teremok_name;
            t_Teremok.teremok_state = teremok_state;
            t_Teremok.teremok_need_update = teremok_need_update;
            t_Teremok.teremok_use_ARM = teremok_use_ARM;
            return t_Teremok;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int teremok_id
        {
            get
            {
                return this._teremok_id;
            }
            set
            {
                this.Onteremok_idChanging(value);
                this._teremok_id = value;
                this.Onteremok_idChanged();
                this.OnPropertyChanged("teremok_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _teremok_id;
        partial void Onteremok_idChanging(int value);
        partial void Onteremok_idChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_name.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_name
        {
            get
            {
                return this._teremok_name;
            }
            set
            {
                this.Onteremok_nameChanging(value);
                this._teremok_name = value;
                this.Onteremok_nameChanged();
                this.OnPropertyChanged("teremok_name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_name;
        partial void Onteremok_nameChanging(string value);
        partial void Onteremok_nameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_address.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_address
        {
            get
            {
                return this._teremok_address;
            }
            set
            {
                this.Onteremok_addressChanging(value);
                this._teremok_address = value;
                this.Onteremok_addressChanged();
                this.OnPropertyChanged("teremok_address");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_address;
        partial void Onteremok_addressChanging(string value);
        partial void Onteremok_addressChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_state.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int teremok_state
        {
            get
            {
                return this._teremok_state;
            }
            set
            {
                this.Onteremok_stateChanging(value);
                this._teremok_state = value;
                this.Onteremok_stateChanged();
                this.OnPropertyChanged("teremok_state");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _teremok_state;
        partial void Onteremok_stateChanging(int value);
        partial void Onteremok_stateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1C.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_1C
        {
            get
            {
                return this._teremok_1C;
            }
            set
            {
                this.Onteremok_1CChanging(value);
                this._teremok_1C = value;
                this.Onteremok_1CChanged();
                this.OnPropertyChanged("teremok_1C");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_1C;
        partial void Onteremok_1CChanging(string value);
        partial void Onteremok_1CChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_need_update.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool teremok_need_update
        {
            get
            {
                return this._teremok_need_update;
            }
            set
            {
                this.Onteremok_need_updateChanging(value);
                this._teremok_need_update = value;
                this.Onteremok_need_updateChanged();
                this.OnPropertyChanged("teremok_need_update");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _teremok_need_update;
        partial void Onteremok_need_updateChanging(bool value);
        partial void Onteremok_need_updateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_pass.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_pass
        {
            get
            {
                return this._teremok_pass;
            }
            set
            {
                this.Onteremok_passChanging(value);
                this._teremok_pass = value;
                this.Onteremok_passChanged();
                this.OnPropertyChanged("teremok_pass");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_pass;
        partial void Onteremok_passChanging(string value);
        partial void Onteremok_passChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_use_ARM.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool teremok_use_ARM
        {
            get
            {
                return this._teremok_use_ARM;
            }
            set
            {
                this.Onteremok_use_ARMChanging(value);
                this._teremok_use_ARM = value;
                this.Onteremok_use_ARMChanged();
                this.OnPropertyChanged("teremok_use_ARM");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _teremok_use_ARM;
        partial void Onteremok_use_ARMChanging(bool value);
        partial void Onteremok_use_ARMChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_prov.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_prov
        {
            get
            {
                return this._teremok_prov;
            }
            set
            {
                this.Onteremok_provChanging(value);
                this._teremok_prov = value;
                this.Onteremok_provChanged();
                this.OnPropertyChanged("teremok_prov");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_prov;
        partial void Onteremok_provChanging(string value);
        partial void Onteremok_provChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_prov_rezerv.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_prov_rezerv
        {
            get
            {
                return this._teremok_prov_rezerv;
            }
            set
            {
                this.Onteremok_prov_rezervChanging(value);
                this._teremok_prov_rezerv = value;
                this.Onteremok_prov_rezervChanged();
                this.OnPropertyChanged("teremok_prov_rezerv");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_prov_rezerv;
        partial void Onteremok_prov_rezervChanging(string value);
        partial void Onteremok_prov_rezervChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa1.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_kassa1
        {
            get
            {
                return this._teremok_kassa1;
            }
            set
            {
                this.Onteremok_kassa1Changing(value);
                this._teremok_kassa1 = value;
                this.Onteremok_kassa1Changed();
                this.OnPropertyChanged("teremok_kassa1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_kassa1;
        partial void Onteremok_kassa1Changing(string value);
        partial void Onteremok_kassa1Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa2.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_kassa2
        {
            get
            {
                return this._teremok_kassa2;
            }
            set
            {
                this.Onteremok_kassa2Changing(value);
                this._teremok_kassa2 = value;
                this.Onteremok_kassa2Changed();
                this.OnPropertyChanged("teremok_kassa2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_kassa2;
        partial void Onteremok_kassa2Changing(string value);
        partial void Onteremok_kassa2Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa3.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_kassa3
        {
            get
            {
                return this._teremok_kassa3;
            }
            set
            {
                this.Onteremok_kassa3Changing(value);
                this._teremok_kassa3 = value;
                this.Onteremok_kassa3Changed();
                this.OnPropertyChanged("teremok_kassa3");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_kassa3;
        partial void Onteremok_kassa3Changing(string value);
        partial void Onteremok_kassa3Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_kassa4.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_kassa4
        {
            get
            {
                return this._teremok_kassa4;
            }
            set
            {
                this.Onteremok_kassa4Changing(value);
                this._teremok_kassa4 = value;
                this.Onteremok_kassa4Changed();
                this.OnPropertyChanged("teremok_kassa4");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_kassa4;
        partial void Onteremok_kassa4Changing(string value);
        partial void Onteremok_kassa4Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm1.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> teremok_numberkkm1
        {
            get
            {
                return this._teremok_numberkkm1;
            }
            set
            {
                this.Onteremok_numberkkm1Changing(value);
                this._teremok_numberkkm1 = value;
                this.Onteremok_numberkkm1Changed();
                this.OnPropertyChanged("teremok_numberkkm1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm1;
        partial void Onteremok_numberkkm1Changing(global::System.Nullable<int> value);
        partial void Onteremok_numberkkm1Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm2.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> teremok_numberkkm2
        {
            get
            {
                return this._teremok_numberkkm2;
            }
            set
            {
                this.Onteremok_numberkkm2Changing(value);
                this._teremok_numberkkm2 = value;
                this.Onteremok_numberkkm2Changed();
                this.OnPropertyChanged("teremok_numberkkm2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm2;
        partial void Onteremok_numberkkm2Changing(global::System.Nullable<int> value);
        partial void Onteremok_numberkkm2Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm3.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> teremok_numberkkm3
        {
            get
            {
                return this._teremok_numberkkm3;
            }
            set
            {
                this.Onteremok_numberkkm3Changing(value);
                this._teremok_numberkkm3 = value;
                this.Onteremok_numberkkm3Changed();
                this.OnPropertyChanged("teremok_numberkkm3");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm3;
        partial void Onteremok_numberkkm3Changing(global::System.Nullable<int> value);
        partial void Onteremok_numberkkm3Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_numberkkm4.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> teremok_numberkkm4
        {
            get
            {
                return this._teremok_numberkkm4;
            }
            set
            {
                this.Onteremok_numberkkm4Changing(value);
                this._teremok_numberkkm4 = value;
                this.Onteremok_numberkkm4Changed();
                this.OnPropertyChanged("teremok_numberkkm4");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _teremok_numberkkm4;
        partial void Onteremok_numberkkm4Changing(global::System.Nullable<int> value);
        partial void Onteremok_numberkkm4Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_parent.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_parent
        {
            get
            {
                return this._teremok_parent;
            }
            set
            {
                this.Onteremok_parentChanging(value);
                this._teremok_parent = value;
                this.Onteremok_parentChanged();
                this.OnPropertyChanged("teremok_parent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_parent;
        partial void Onteremok_parentChanging(string value);
        partial void Onteremok_parentChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1c82.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> teremok_1c82
        {
            get
            {
                return this._teremok_1c82;
            }
            set
            {
                this.Onteremok_1c82Changing(value);
                this._teremok_1c82 = value;
                this.Onteremok_1c82Changed();
                this.OnPropertyChanged("teremok_1c82");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _teremok_1c82;
        partial void Onteremok_1c82Changing(global::System.Nullable<int> value);
        partial void Onteremok_1c82Changed();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_1c82_date.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> teremok_1c82_date
        {
            get
            {
                return this._teremok_1c82_date;
            }
            set
            {
                this.Onteremok_1c82_dateChanging(value);
                this._teremok_1c82_date = value;
                this.Onteremok_1c82_dateChanged();
                this.OnPropertyChanged("teremok_1c82_date");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _teremok_1c82_date;
        partial void Onteremok_1c82_dateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onteremok_1c82_dateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства deleted.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this.OndeletedChanging(value);
                this._deleted = value;
                this.OndeletedChanged();
                this.OnPropertyChanged("deleted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _deleted;
        partial void OndeletedChanging(global::System.Nullable<bool> value);
        partial void OndeletedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ip.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ip
        {
            get
            {
                return this._ip;
            }
            set
            {
                this.OnipChanging(value);
                this._ip = value;
                this.OnipChanged();
                this.OnPropertyChanged("ip");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ip;
        partial void OnipChanging(string value);
        partial void OnipChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства teremok_city.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string teremok_city
        {
            get
            {
                return this._teremok_city;
            }
            set
            {
                this.Onteremok_cityChanging(value);
                this._teremok_city = value;
                this.Onteremok_cityChanged();
                this.OnPropertyChanged("teremok_city");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _teremok_city;
        partial void Onteremok_cityChanging(string value);
        partial void Onteremok_cityChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства original_id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> original_id
        {
            get
            {
                return this._original_id;
            }
            set
            {
                this.Onoriginal_idChanging(value);
                this._original_id = value;
                this.Onoriginal_idChanged();
                this.OnPropertyChanged("original_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _original_id;
        partial void Onoriginal_idChanging(global::System.Nullable<int> value);
        partial void Onoriginal_idChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
