//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5485
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets91EFAF1AD1E27C29D845CEF7D537A812))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// Тип содержит представления для наборов EntitySet и AssociationSet, созданные во время разработки.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets91EFAF1AD1E27C29D845CEF7D537A812 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// Конструктор хранит представления для экстентов и значения хэша, созданные на основе замыканий и представлений метаданных и сопоставлений.
        /// </Summary>
        public ViewsForBaseEntitySets91EFAF1AD1E27C29D845CEF7D537A812()
        {
            this.EdmEntityContainerName = "RBMEntities";
            this.StoreEntityContainerName = "RBMModelStoreContainer";
            this.HashOverMappingClosure = "d08e013d9631008e00b82b875991fe3a";
            this.HashOverAllExtentViews = "9b3813f43981d60a88d3a4f73014987f";
            this.ViewCount = 14;
        }
        
        // Метод возвращает представление для указанного индекса.
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                // возвратить представление для RBMModelStoreContainer.t_WebInfo
                return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_WebInfo", @"
    SELECT VALUE -- Constructing t_WebInfo
        [RBMModel.Store].t_WebInfo(T1.[t_WebInfo.id], T1.[t_WebInfo.header], T1.[t_WebInfo.message], T1.[t_WebInfo.date], T1.[t_WebInfo.type], T1.[t_WebInfo.ip])
    FROM (
        SELECT 
            T.id AS [t_WebInfo.id], 
            T.header AS [t_WebInfo.header], 
            T.message AS [t_WebInfo.message], 
            T.date AS [t_WebInfo.date], 
            T.type AS [t_WebInfo.type], 
            T.ip AS [t_WebInfo.ip], 
            True AS _from0
        FROM RBMEntities.t_WebInfo AS T
    ) AS T1");
            }
            else
            {
                if ((index == 1))
                {
                    // возвратить представление для RBMEntities.t_WebInfo
                    return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_WebInfo", @"
    SELECT VALUE -- Constructing t_WebInfo
        RBMModel.t_WebInfo(T1.[t_WebInfo.id], T1.[t_WebInfo.header], T1.[t_WebInfo.message], T1.[t_WebInfo.type], T1.[t_WebInfo.date], T1.[t_WebInfo.ip])
    FROM (
        SELECT 
            T.id AS [t_WebInfo.id], 
            T.header AS [t_WebInfo.header], 
            T.message AS [t_WebInfo.message], 
            T.type AS [t_WebInfo.type], 
            T.date AS [t_WebInfo.date], 
            T.ip AS [t_WebInfo.ip], 
            True AS _from0
        FROM RBMModelStoreContainer.t_WebInfo AS T
    ) AS T1");
                }
                else
                {
                    if ((index == 2))
                    {
                        // возвратить представление для RBMModelStoreContainer.t_Web_kkm_z_info
                        return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_Web_kkm_z_info", @"
    SELECT VALUE -- Constructing t_Web_kkm_z_info
        [RBMModel.Store].t_Web_kkm_z_info(T1.[t_Web_kkm_z_info.id], T1.[t_Web_kkm_z_info.terem_1c], T1.[t_Web_kkm_z_info.num_kkm], T1.[t_Web_kkm_z_info.zfile], T1.[t_Web_kkm_z_info.zdate], T1.[t_Web_kkm_z_info.datetime], T1.[t_Web_kkm_z_info.worked], T1.[t_Web_kkm_z_info.lasttime_online], T1.[t_Web_kkm_z_info.date_recieved], T1.[t_Web_kkm_z_info.zsended], T1.[t_Web_kkm_z_info.is_online], T1.[t_Web_kkm_z_info.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_kkm_z_info.id], 
            T.terem_1c AS [t_Web_kkm_z_info.terem_1c], 
            T.num_kkm AS [t_Web_kkm_z_info.num_kkm], 
            T.zfile AS [t_Web_kkm_z_info.zfile], 
            T.zdate AS [t_Web_kkm_z_info.zdate], 
            T.datetime AS [t_Web_kkm_z_info.datetime], 
            T.worked AS [t_Web_kkm_z_info.worked], 
            T.lasttime_online AS [t_Web_kkm_z_info.lasttime_online], 
            T.date_recieved AS [t_Web_kkm_z_info.date_recieved], 
            T.zsended AS [t_Web_kkm_z_info.zsended], 
            T.is_online AS [t_Web_kkm_z_info.is_online], 
            T.shift_num AS [t_Web_kkm_z_info.shift_num], 
            True AS _from0
        FROM RBMEntities.t_Web_kkm_z_info AS T
    ) AS T1");
                    }
                    else
                    {
                        if ((index == 3))
                        {
                            // возвратить представление для RBMEntities.t_Web_kkm_z_info
                            return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_Web_kkm_z_info", @"
    SELECT VALUE -- Constructing t_Web_kkm_z_info
        RBMModel.t_Web_kkm_z_info(T1.[t_Web_kkm_z_info.id], T1.[t_Web_kkm_z_info.terem_1c], T1.[t_Web_kkm_z_info.num_kkm], T1.[t_Web_kkm_z_info.zfile], T1.[t_Web_kkm_z_info.zdate], T1.[t_Web_kkm_z_info.datetime], T1.[t_Web_kkm_z_info.worked], T1.[t_Web_kkm_z_info.lasttime_online], T1.[t_Web_kkm_z_info.date_recieved], T1.[t_Web_kkm_z_info.zsended], T1.[t_Web_kkm_z_info.is_online], T1.[t_Web_kkm_z_info.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_kkm_z_info.id], 
            T.terem_1c AS [t_Web_kkm_z_info.terem_1c], 
            T.num_kkm AS [t_Web_kkm_z_info.num_kkm], 
            T.zfile AS [t_Web_kkm_z_info.zfile], 
            T.zdate AS [t_Web_kkm_z_info.zdate], 
            T.datetime AS [t_Web_kkm_z_info.datetime], 
            T.worked AS [t_Web_kkm_z_info.worked], 
            T.lasttime_online AS [t_Web_kkm_z_info.lasttime_online], 
            T.date_recieved AS [t_Web_kkm_z_info.date_recieved], 
            T.zsended AS [t_Web_kkm_z_info.zsended], 
            T.is_online AS [t_Web_kkm_z_info.is_online], 
            T.shift_num AS [t_Web_kkm_z_info.shift_num], 
            True AS _from0
        FROM RBMModelStoreContainer.t_Web_kkm_z_info AS T
    ) AS T1");
                        }
                        else
                        {
                            if ((index == 4))
                            {
                                // возвратить представление для RBMModelStoreContainer.t_Teremok
                                return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_Teremok", "\r\n    SELECT VALUE -- Constructing t_Teremok\r\n        [RBMModel.Store].t_Teremok(" +
                                        "T1.[t_Teremok.teremok_id], T1.[t_Teremok.teremok_name], T1.[t_Teremok.teremok_ad" +
                                        "dress], T1.[t_Teremok.teremok_state], T1.[t_Teremok.teremok_1C], T1.[t_Teremok.t" +
                                        "eremok_need_update], T1.[t_Teremok.teremok_pass], T1.[t_Teremok.teremok_use_ARM]" +
                                        ", T1.[t_Teremok.teremok_prov], T1.[t_Teremok.teremok_prov_rezerv], T1.[t_Teremok" +
                                        ".teremok_kassa1], T1.[t_Teremok.teremok_kassa2], T1.[t_Teremok.teremok_kassa3], " +
                                        "T1.[t_Teremok.teremok_kassa4], T1.[t_Teremok.teremok_numberkkm1], T1.[t_Teremok." +
                                        "teremok_numberkkm2], T1.[t_Teremok.teremok_numberkkm3], T1.[t_Teremok.teremok_nu" +
                                        "mberkkm4], T1.[t_Teremok.teremok_parent], T1.[t_Teremok.teremok_1c82], T1.[t_Ter" +
                                        "emok.teremok_1c82_date], T1.[t_Teremok.deleted], T1.[t_Teremok.ip], T1.[t_Teremo" +
                                        "k.teremok_city], T1.[t_Teremok.original_id])\r\n    FROM (\r\n        SELECT \r\n     " +
                                        "       T.teremok_id AS [t_Teremok.teremok_id], \r\n            T.teremok_name AS [" +
                                        "t_Teremok.teremok_name], \r\n            T.teremok_address AS [t_Teremok.teremok_a" +
                                        "ddress], \r\n            T.teremok_state AS [t_Teremok.teremok_state], \r\n         " +
                                        "   T.teremok_1C AS [t_Teremok.teremok_1C], \r\n            T.teremok_need_update A" +
                                        "S [t_Teremok.teremok_need_update], \r\n            T.teremok_pass AS [t_Teremok.te" +
                                        "remok_pass], \r\n            T.teremok_use_ARM AS [t_Teremok.teremok_use_ARM], \r\n " +
                                        "           T.teremok_prov AS [t_Teremok.teremok_prov], \r\n            T.teremok_p" +
                                        "rov_rezerv AS [t_Teremok.teremok_prov_rezerv], \r\n            T.teremok_kassa1 AS" +
                                        " [t_Teremok.teremok_kassa1], \r\n            T.teremok_kassa2 AS [t_Teremok.teremo" +
                                        "k_kassa2], \r\n            T.teremok_kassa3 AS [t_Teremok.teremok_kassa3], \r\n     " +
                                        "       T.teremok_kassa4 AS [t_Teremok.teremok_kassa4], \r\n            T.teremok_n" +
                                        "umberkkm1 AS [t_Teremok.teremok_numberkkm1], \r\n            T.teremok_numberkkm2 " +
                                        "AS [t_Teremok.teremok_numberkkm2], \r\n            T.teremok_numberkkm3 AS [t_Tere" +
                                        "mok.teremok_numberkkm3], \r\n            T.teremok_numberkkm4 AS [t_Teremok.teremo" +
                                        "k_numberkkm4], \r\n            T.teremok_parent AS [t_Teremok.teremok_parent], \r\n " +
                                        "           T.teremok_1c82 AS [t_Teremok.teremok_1c82], \r\n            T.teremok_1" +
                                        "c82_date AS [t_Teremok.teremok_1c82_date], \r\n            T.deleted AS [t_Teremok" +
                                        ".deleted], \r\n            T.ip AS [t_Teremok.ip], \r\n            T.teremok_city AS" +
                                        " [t_Teremok.teremok_city], \r\n            T.original_id AS [t_Teremok.original_id" +
                                        "], \r\n            True AS _from0\r\n        FROM RBMEntities.t_Teremok AS T\r\n    ) " +
                                        "AS T1");
                            }
                            else
                            {
                                if ((index == 5))
                                {
                                    // возвратить представление для RBMEntities.t_Teremok
                                    return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_Teremok", "\r\n    SELECT VALUE -- Constructing t_Teremok\r\n        RBMModel.t_Teremok(T1.[t_Te" +
                                            "remok.teremok_id], T1.[t_Teremok.teremok_name], T1.[t_Teremok.teremok_address], " +
                                            "T1.[t_Teremok.teremok_state], T1.[t_Teremok.teremok_1C], T1.[t_Teremok.teremok_n" +
                                            "eed_update], T1.[t_Teremok.teremok_pass], T1.[t_Teremok.teremok_use_ARM], T1.[t_" +
                                            "Teremok.teremok_prov], T1.[t_Teremok.teremok_prov_rezerv], T1.[t_Teremok.teremok" +
                                            "_kassa1], T1.[t_Teremok.teremok_kassa2], T1.[t_Teremok.teremok_kassa3], T1.[t_Te" +
                                            "remok.teremok_kassa4], T1.[t_Teremok.teremok_numberkkm1], T1.[t_Teremok.teremok_" +
                                            "numberkkm2], T1.[t_Teremok.teremok_numberkkm3], T1.[t_Teremok.teremok_numberkkm4" +
                                            "], T1.[t_Teremok.teremok_parent], T1.[t_Teremok.teremok_1c82], T1.[t_Teremok.ter" +
                                            "emok_1c82_date], T1.[t_Teremok.deleted], T1.[t_Teremok.ip], T1.[t_Teremok.teremo" +
                                            "k_city], T1.[t_Teremok.original_id])\r\n    FROM (\r\n        SELECT \r\n            T" +
                                            ".teremok_id AS [t_Teremok.teremok_id], \r\n            T.teremok_name AS [t_Teremo" +
                                            "k.teremok_name], \r\n            T.teremok_address AS [t_Teremok.teremok_address]," +
                                            " \r\n            T.teremok_state AS [t_Teremok.teremok_state], \r\n            T.ter" +
                                            "emok_1C AS [t_Teremok.teremok_1C], \r\n            T.teremok_need_update AS [t_Ter" +
                                            "emok.teremok_need_update], \r\n            T.teremok_pass AS [t_Teremok.teremok_pa" +
                                            "ss], \r\n            T.teremok_use_ARM AS [t_Teremok.teremok_use_ARM], \r\n         " +
                                            "   T.teremok_prov AS [t_Teremok.teremok_prov], \r\n            T.teremok_prov_reze" +
                                            "rv AS [t_Teremok.teremok_prov_rezerv], \r\n            T.teremok_kassa1 AS [t_Tere" +
                                            "mok.teremok_kassa1], \r\n            T.teremok_kassa2 AS [t_Teremok.teremok_kassa2" +
                                            "], \r\n            T.teremok_kassa3 AS [t_Teremok.teremok_kassa3], \r\n            T" +
                                            ".teremok_kassa4 AS [t_Teremok.teremok_kassa4], \r\n            T.teremok_numberkkm" +
                                            "1 AS [t_Teremok.teremok_numberkkm1], \r\n            T.teremok_numberkkm2 AS [t_Te" +
                                            "remok.teremok_numberkkm2], \r\n            T.teremok_numberkkm3 AS [t_Teremok.tere" +
                                            "mok_numberkkm3], \r\n            T.teremok_numberkkm4 AS [t_Teremok.teremok_number" +
                                            "kkm4], \r\n            T.teremok_parent AS [t_Teremok.teremok_parent], \r\n         " +
                                            "   T.teremok_1c82 AS [t_Teremok.teremok_1c82], \r\n            T.teremok_1c82_date" +
                                            " AS [t_Teremok.teremok_1c82_date], \r\n            T.deleted AS [t_Teremok.deleted" +
                                            "], \r\n            T.ip AS [t_Teremok.ip], \r\n            T.teremok_city AS [t_Tere" +
                                            "mok.teremok_city], \r\n            T.original_id AS [t_Teremok.original_id], \r\n   " +
                                            "         True AS _from0\r\n        FROM RBMModelStoreContainer.t_Teremok AS T\r\n   " +
                                            " ) AS T1");
                                }
                                else
                                {
                                    if ((index == 6))
                                    {
                                        // возвратить представление для RBMModelStoreContainer.t_kkm
                                        return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_kkm", @"
    SELECT VALUE -- Constructing t_kkm
        [RBMModel.Store].t_kkm(T1.[t_kkm.kkm_uid], T1.[t_kkm.kkm_id], T1.[t_kkm.teremok_1c], T1.[t_kkm.domain_name], T1.[t_kkm.domain_main_suffix], T1.[t_kkm.date_updated], T1.[t_kkm.hostname_confirmed], T1.[t_kkm.dom_suffix_confirmed], T1.[t_kkm.date_confirmed], T1.[t_kkm.date_state_updated], T1.[t_kkm.isOnline7], T1.[t_kkm.city])
    FROM (
        SELECT 
            T.kkm_uid AS [t_kkm.kkm_uid], 
            T.kkm_id AS [t_kkm.kkm_id], 
            T.teremok_1c AS [t_kkm.teremok_1c], 
            T.domain_name AS [t_kkm.domain_name], 
            T.domain_main_suffix AS [t_kkm.domain_main_suffix], 
            T.date_updated AS [t_kkm.date_updated], 
            T.hostname_confirmed AS [t_kkm.hostname_confirmed], 
            T.dom_suffix_confirmed AS [t_kkm.dom_suffix_confirmed], 
            T.date_confirmed AS [t_kkm.date_confirmed], 
            T.date_state_updated AS [t_kkm.date_state_updated], 
            T.isOnline7 AS [t_kkm.isOnline7], 
            T.city AS [t_kkm.city], 
            True AS _from0
        FROM RBMEntities.t_kkm AS T
    ) AS T1");
                                    }
                                    else
                                    {
                                        if ((index == 7))
                                        {
                                            // возвратить представление для RBMEntities.t_kkm
                                            return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_kkm", @"
    SELECT VALUE -- Constructing t_kkm
        RBMModel.t_kkm(T1.[t_kkm.kkm_uid], T1.[t_kkm.kkm_id], T1.[t_kkm.teremok_1c], T1.[t_kkm.domain_name], T1.[t_kkm.domain_main_suffix], T1.[t_kkm.date_updated], T1.[t_kkm.hostname_confirmed], T1.[t_kkm.dom_suffix_confirmed], T1.[t_kkm.date_confirmed], T1.[t_kkm.date_state_updated], T1.[t_kkm.isOnline7], T1.[t_kkm.city])
    FROM (
        SELECT 
            T.kkm_uid AS [t_kkm.kkm_uid], 
            T.kkm_id AS [t_kkm.kkm_id], 
            T.teremok_1c AS [t_kkm.teremok_1c], 
            T.domain_name AS [t_kkm.domain_name], 
            T.domain_main_suffix AS [t_kkm.domain_main_suffix], 
            T.date_updated AS [t_kkm.date_updated], 
            T.hostname_confirmed AS [t_kkm.hostname_confirmed], 
            T.dom_suffix_confirmed AS [t_kkm.dom_suffix_confirmed], 
            T.date_confirmed AS [t_kkm.date_confirmed], 
            T.date_state_updated AS [t_kkm.date_state_updated], 
            T.isOnline7 AS [t_kkm.isOnline7], 
            T.city AS [t_kkm.city], 
            True AS _from0
        FROM RBMModelStoreContainer.t_kkm AS T
    ) AS T1");
                                        }
                                        else
                                        {
                                            if ((index == 8))
                                            {
                                                // возвратить представление для RBMModelStoreContainer.t_Web_ZReport
                                                return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_Web_ZReport", @"
    SELECT VALUE -- Constructing t_Web_ZReport
        [RBMModel.Store].t_Web_ZReport(T1.[t_Web_ZReport.id], T1.[t_Web_ZReport.terem_1c], T1.[t_Web_ZReport.kkm_num], T1.[t_Web_ZReport.date_recieved], T1.[t_Web_ZReport.zdate], T1.[t_Web_ZReport.zfile], T1.[t_Web_ZReport.zdata], T1.[t_Web_ZReport.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_ZReport.id], 
            T.terem_1c AS [t_Web_ZReport.terem_1c], 
            T.kkm_num AS [t_Web_ZReport.kkm_num], 
            T.date_recieved AS [t_Web_ZReport.date_recieved], 
            T.zdate AS [t_Web_ZReport.zdate], 
            T.zfile AS [t_Web_ZReport.zfile], 
            T.zdata AS [t_Web_ZReport.zdata], 
            T.shift_num AS [t_Web_ZReport.shift_num], 
            True AS _from0
        FROM RBMEntities.t_Web_ZReport AS T
    ) AS T1");
                                            }
                                            else
                                            {
                                                if ((index == 9))
                                                {
                                                    // возвратить представление для RBMEntities.t_Web_ZReport
                                                    return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_Web_ZReport", @"
    SELECT VALUE -- Constructing t_Web_ZReport
        RBMModel.t_Web_ZReport(T1.[t_Web_ZReport.id], T1.[t_Web_ZReport.terem_1c], T1.[t_Web_ZReport.kkm_num], T1.[t_Web_ZReport.date_recieved], T1.[t_Web_ZReport.zdate], T1.[t_Web_ZReport.zfile], T1.[t_Web_ZReport.zdata], T1.[t_Web_ZReport.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_ZReport.id], 
            T.terem_1c AS [t_Web_ZReport.terem_1c], 
            T.kkm_num AS [t_Web_ZReport.kkm_num], 
            T.date_recieved AS [t_Web_ZReport.date_recieved], 
            T.zdate AS [t_Web_ZReport.zdate], 
            T.zfile AS [t_Web_ZReport.zfile], 
            T.zdata AS [t_Web_ZReport.zdata], 
            T.shift_num AS [t_Web_ZReport.shift_num], 
            True AS _from0
        FROM RBMModelStoreContainer.t_Web_ZReport AS T
    ) AS T1");
                                                }
                                                else
                                                {
                                                    if ((index == 10))
                                                    {
                                                        // возвратить представление для RBMModelStoreContainer.t_Web_Test_table
                                                        return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_Web_Test_table", @"
    SELECT VALUE -- Constructing t_Web_Test_table
        [RBMModel.Store].t_Web_Test_table(T1.[t_Web_Test_table.id], T1.[t_Web_Test_table.terem], T1.[t_Web_Test_table.kkm], T1.[t_Web_Test_table.zfile], T1.[t_Web_Test_table.zdate], T1.[t_Web_Test_table.datetime], T1.[t_Web_Test_table.worked], T1.[t_Web_Test_table.lasttime_online], T1.[t_Web_Test_table.date_recieved], T1.[t_Web_Test_table.zsended], T1.[t_Web_Test_table.is_online], T1.[t_Web_Test_table.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_Test_table.id], 
            T.terem AS [t_Web_Test_table.terem], 
            T.kkm AS [t_Web_Test_table.kkm], 
            T.zfile AS [t_Web_Test_table.zfile], 
            T.zdate AS [t_Web_Test_table.zdate], 
            T.datetime AS [t_Web_Test_table.datetime], 
            T.worked AS [t_Web_Test_table.worked], 
            T.lasttime_online AS [t_Web_Test_table.lasttime_online], 
            T.date_recieved AS [t_Web_Test_table.date_recieved], 
            T.zsended AS [t_Web_Test_table.zsended], 
            T.is_online AS [t_Web_Test_table.is_online], 
            T.shift_num AS [t_Web_Test_table.shift_num], 
            True AS _from0
        FROM RBMEntities.t_Web_Test_table AS T
    ) AS T1");
                                                    }
                                                    else
                                                    {
                                                        if ((index == 11))
                                                        {
                                                            // возвратить представление для RBMEntities.t_Web_Test_table
                                                            return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_Web_Test_table", @"
    SELECT VALUE -- Constructing t_Web_Test_table
        RBMModel.t_Web_Test_table(T1.[t_Web_Test_table.id], T1.[t_Web_Test_table.terem], T1.[t_Web_Test_table.kkm], T1.[t_Web_Test_table.zfile], T1.[t_Web_Test_table.zdate], T1.[t_Web_Test_table.datetime], T1.[t_Web_Test_table.worked], T1.[t_Web_Test_table.lasttime_online], T1.[t_Web_Test_table.date_recieved], T1.[t_Web_Test_table.zsended], T1.[t_Web_Test_table.is_online], T1.[t_Web_Test_table.shift_num])
    FROM (
        SELECT 
            T.id AS [t_Web_Test_table.id], 
            T.terem AS [t_Web_Test_table.terem], 
            T.kkm AS [t_Web_Test_table.kkm], 
            T.zfile AS [t_Web_Test_table.zfile], 
            T.zdate AS [t_Web_Test_table.zdate], 
            T.datetime AS [t_Web_Test_table.datetime], 
            T.worked AS [t_Web_Test_table.worked], 
            T.lasttime_online AS [t_Web_Test_table.lasttime_online], 
            T.date_recieved AS [t_Web_Test_table.date_recieved], 
            T.zsended AS [t_Web_Test_table.zsended], 
            T.is_online AS [t_Web_Test_table.is_online], 
            T.shift_num AS [t_Web_Test_table.shift_num], 
            True AS _from0
        FROM RBMModelStoreContainer.t_Web_Test_table AS T
    ) AS T1");
                                                        }
                                                        else
                                                        {
                                                            if ((index == 12))
                                                            {
                                                                // возвратить представление для RBMModelStoreContainer.t_Web_FilesLog
                                                                return new System.Collections.Generic.KeyValuePair<string, string>("RBMModelStoreContainer.t_Web_FilesLog", @"
    SELECT VALUE -- Constructing t_Web_FilesLog
        [RBMModel.Store].t_Web_FilesLog(T1.[t_Web_FilesLog.id], T1.[t_Web_FilesLog.terem_1c], T1.[t_Web_FilesLog.kkm_num], T1.[t_Web_FilesLog.type], T1.[t_Web_FilesLog.folder], T1.[t_Web_FilesLog.afile], T1.[t_Web_FilesLog.length], T1.[t_Web_FilesLog.date_recieved], T1.[t_Web_FilesLog.date_deleted], T1.[t_Web_FilesLog.info], T1.[t_Web_FilesLog.object])
    FROM (
        SELECT 
            T.id AS [t_Web_FilesLog.id], 
            T.terem_1c AS [t_Web_FilesLog.terem_1c], 
            T.kkm_num AS [t_Web_FilesLog.kkm_num], 
            T.type AS [t_Web_FilesLog.type], 
            T.folder AS [t_Web_FilesLog.folder], 
            T.afile AS [t_Web_FilesLog.afile], 
            T.length AS [t_Web_FilesLog.length], 
            T.date_recieved AS [t_Web_FilesLog.date_recieved], 
            T.date_deleted AS [t_Web_FilesLog.date_deleted], 
            T.info AS [t_Web_FilesLog.info], 
            T.object AS [t_Web_FilesLog.object], 
            True AS _from0
        FROM RBMEntities.t_Web_FilesLog AS T
    ) AS T1");
                                                            }
                                                            else
                                                            {
                                                                if ((index == 13))
                                                                {
                                                                    // возвратить представление для RBMEntities.t_Web_FilesLog
                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("RBMEntities.t_Web_FilesLog", @"
    SELECT VALUE -- Constructing t_Web_FilesLog
        RBMModel.t_Web_FilesLog(T1.[t_Web_FilesLog.id], T1.[t_Web_FilesLog.terem_1c], T1.[t_Web_FilesLog.kkm_num], T1.[t_Web_FilesLog.type], T1.[t_Web_FilesLog.folder], T1.[t_Web_FilesLog.afile], T1.[t_Web_FilesLog.length], T1.[t_Web_FilesLog.date_recieved], T1.[t_Web_FilesLog.date_deleted], T1.[t_Web_FilesLog.info], T1.[t_Web_FilesLog.object])
    FROM (
        SELECT 
            T.id AS [t_Web_FilesLog.id], 
            T.terem_1c AS [t_Web_FilesLog.terem_1c], 
            T.kkm_num AS [t_Web_FilesLog.kkm_num], 
            T.type AS [t_Web_FilesLog.type], 
            T.folder AS [t_Web_FilesLog.folder], 
            T.afile AS [t_Web_FilesLog.afile], 
            T.length AS [t_Web_FilesLog.length], 
            T.date_recieved AS [t_Web_FilesLog.date_recieved], 
            T.date_deleted AS [t_Web_FilesLog.date_deleted], 
            T.info AS [t_Web_FilesLog.info], 
            T.object AS [t_Web_FilesLog.object], 
            True AS _from0
        FROM RBMModelStoreContainer.t_Web_FilesLog AS T
    ) AS T1");
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            throw new System.IndexOutOfRangeException();
        }
    }
}
